version: "3.3"
services:
  #  logs:
  #    image: gliderlabs/logspout
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:12.1-alpine
    restart: always
    volumes:
      - ./docker/dbschemas:/docker-entrypoint-initdb.d
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
  rabbitmq:
    image: bitnami/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
    links:
      - rabbitmq
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
      - RABBIT_USER=user
      - RABBIT_PASSWORD=bitnami
  #  prometheus:
  #    image: prom/prometheus
  #    volumes:
  #      - ./docker/prometheus/:/etc/prometheus/
  #    command: '--beats.conf.file=/etc/prometheus/beats.conf.yaml'
  #    ports:
  #      - 9090:9090
  #    #-------------------------
  #    # DOCKER HOST IP COMMAND
  #    # run <ifconfig>, then look for 'docker0' of <inet address>
  #    #-------------------------
  #    extra_hosts:
  #      - "appdockerhost:172.17.0.1"
  #  grafana:
  #    image: grafana/grafana
  #    volumes:
  #      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
  #    environment:
  #      - GF_SECURITY_ADMIN_PASSWORD=admin
  #      - GF_USERS_ALLOW_SIGN_UP=false
  #      - GF_INSTALL_PLUGINS=grafana-piechart-panel
  #    ports:
  #      - 13000:3000
  #    links:
  #      - prometheus
  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  logstash:
    image: logstash:7.9.2
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    links:
      - elasticsearch
  kibana:
    image: kibana:7.9.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    links:
      - elasticsearch