### OrderPlaced
POST http://localhost:8080/sales
Content-Type: application/json

{
  "orderItems": [
    {
      "itemId": "1",
      "quantity": 3
    }
  ],
  "customerId": "1"
}

### GET Orders
GET http://localhost:8080/sales

> {%
client.global.set("orderId", response.body[0].orderId);
%}

### OrderModified
POST http://localhost:8080/sales/{{orderId}}
Content-Type: application/json

{
  "orderItems": [
    {
      "itemId": "1",
      "quantity": 5
    }
  ]
}

### OrderCancelled
POST http://localhost:8080/sales/{{orderId}}/cancel
Content-Type: application/json

{
  "reason": "Mistakenly order has been placed."
}

### GET Order by ID
GET http://localhost:8080/sales/{{orderId}}