create table inventory (
    id bigint generated by default as identity,
    inventory_id varchar(36) not null ,
    inventory_name varchar(255),
    primary key (id)
);

create table inventory_item (
    id bigint generated by default as identity,
    item_id   varchar(36) not null ,
    item_name varchar(255),
    item_desc varchar(255),
    price     decimal,
    quantity  integer,
    primary key (id)
);

alter table inventory
       add constraint UK_inventory_id unique (inventory_id);

alter table inventory_item
       add constraint UK_inventory_item_id unique (item_id);