spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: inventory
    password: inventory
    url: jdbc:postgresql://localhost:5432/inventory
  rabbitmq:
    username: user
    password: bitnami
    host: localhost
    port: 5672
server:
  port: 8082