spring:
  application:
    name: FulfillmentService
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        orderPlaced: # [SubscribableChannel]
          destination: order.placed
          group: fulfillment
        orderModified: # [SubscribableChannel]
          destination: order.modified
          group: fulfillment
        orderCancelled: # [SubscribableChannel]
          destination: order.cancelled
          group: fulfillment
        orderBilled: # [SubscribableChannel]
          destination: order.billed
          group: fulfillment
        modificationBilled: # [SubscribableChannel]
          destination: modification.billed
          group: fulfillment
        orderShipped: # [MessageChannel]
          destination: order.shipped
  zipkin:
    sender:
      type: web
  main:
    register-shutdown-hook: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
server:
  shutdown: graceful
logging:
  register-shutdown-hook: true