#   APP PROPERTIES
#------------------------------------------
InventoryService:
  url: http://localhost:8080
#------------------------------------------
spring:
  application:
    name: BillingService
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        orderPlaced: # [SubscribableChannel]
          destination: order.placed
          group: billing
        orderModified: # [SubscribableChannel]
          destination: order.modified
          group: billing
        orderCancelled: # [SubscribableChannel]
          destination: order.cancelled
          group: billing
        orderBilled: # [MessageChannel]
          destination: order.billed
        modificationBilled: # [MessageChannel]
          destination: modification.billed
        orderRefunded: # [MessageChannel]
          destination: order.refunded
  zipkin:
    sender:
      type: web
  main:
    register-shutdown-hook: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
server:
  shutdown: graceful
logging:
  register-shutdown-hook: true