spring:
  application:
    name: NotificationService
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        orderPlaced: # [SubscribableChannel]
          destination: order.placed
          group: notification
        orderShipped: # [SubscribableChannel]
          destination: order.shipped
          group: notification
        orderRefunded: # [SubscribableChannel]
          destination: order.refunded
          group: notification
  zipkin:
    sender:
      type: web
  main:
    register-shutdown-hook: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
server:
  shutdown: graceful
logging:
  register-shutdown-hook: true
