### OrderPlaced

POST http://localhost:8080/sales
Content-Type: application/json

{
  "orderItems": [
    {
      "itemId": "1",
      "quantity": 3
    }
  ],
  "customerId": "1"
}


### GET Orders
GET http://localhost:8080/sales