global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'CaseStudy'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'Microservices'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'appdockerhost:8081' ]
        labels:
          application: 'billing-service'
      - targets: [ 'appdockerhost:8082' ]
        labels:
          application: 'fullfilment-service'
      - targets: [ 'appdockerhost:8083' ]
        labels:
          application: 'inventory-service'
      - targets: [ 'appdockerhost:8084' ]
        labels:
          application: 'notification-service'
      - targets: [ 'appdockerhost:8085' ]
        labels:
          application: 'sales-service'
  - job_name: 'Plugins'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'appdockerhost:8080' ]
        labels:
          application: 'ApiGatewayService'
  - job_name: 'Supports'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'appdockerhost:9090' ]
        labels:
          application: 'Prometheus'