mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  application:
    name: inventory-service
  profiles:
    active: dev
  zipkin:
    sender:
      type: web
  main:
    register-shutdown-hook: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
server:
  shutdown: graceful
logging:
  register-shutdown-hook: true