mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  application:
    name: InventoryService
  profiles:
    active: dev
  zipkin:
    sender:
      type: web
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info